name: Express CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.dev
          load: true
          tags: shrempf/express-docker:test

      - name: Test
        run: |
          docker run --rm shrempf/express-docker:test

      - name: Publish
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: shrempf/express-docker:latest
